apiVersion: batch/v1
kind: Job
metadata:
  name: nginx-check-job
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl:latest
        command: ["sh", "-c"]
        args:
          - |
            echo "Checking NGINX homepage...";
            sleep 5;
            curl -I http://nginx-service:80;
      restartPolicy: Never
  backoffLimit: 3
