version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  sqlpad:
    image: sqlpad/sqlpad:latest
    container_name: sqlpad-two
    environment:
      SQLPAD_ADMIN: admin@admin.com
      SQLPAD_ADMIN_PASSWORD: admin123
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
