apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
spec:
  type: NodePort
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: {{ .Values.mongoExpress.port }}
      targetPort: {{ .Values.mongoExpress.port }}
      nodePort: {{ .Values.mongoExpress.nodePort }}
